#pragma once

#include "quantpulse/domain/strategy/StrategyEngine.hpp"

namespace quantpulse::domain::execution
{

    enum class OrderSide
    {
        None,
        Buy,
        Sell
    };

    struct ExecutionDecision
    {
        OrderSide orderSide;

        bool shouldExecute;
    };

    class ExecutionEngine
    {
    public:
        /**
         * @brief Convert a strategy action into an execution decision.
         *
         * Strategy actions are translated as follows:
         *
         * Hold
         *     -> no order
         *
         * EnterLong
         *     -> buy order
         *
         * ExitLong
         *     -> sell order
         *
         * @param action Strategy action generated by the strategy engine.
         *
         * @return Execution decision describing whether an order
         *         should be executed and its side.
         */
        [[nodiscard]]
        static ExecutionDecision evaluate(
            strategy::StrategyAction action);
    };

} // namespace quantpulse::domain::execution