#include "quantpulse/domain/trading/TradingEngine.hpp"

#include <stdexcept>

namespace quantpulse::domain::trading
{

    TradingDecision TradingEngine::evaluate(
        const TradingRequest &request,
        const TradingConfig &config)
    {
        /*
         * ----------------------------------------------------
         * STEP 1
         * Strategy evaluation
         * ----------------------------------------------------
         */
        const auto strategyDecision =
            strategy::StrategyEngine::evaluate(
                request.signal,
                request.currentPosition,
                config.entryThreshold,
                config.exitThreshold);

        /*
         * ----------------------------------------------------
         * HOLD PATH
         * ----------------------------------------------------
         *
         * No trade is being proposed.
         *
         * Therefore:
         *
         * - no position sizing is required
         * - no additional risk is introduced
         * - no execution is required
         */
        if (strategyDecision.action ==
            strategy::StrategyAction::Hold)
        {
            return TradingDecision{
                strategyDecision,

                sizing::PositionSizingResult{
                    0.0,
                    0.0,
                    0.0},

                risk_management::RiskDecision{
                    true,
                    false,
                    false,
                    false},

                execution::ExecutionDecision{
                    execution::OrderSide::None,
                    false}};
        }

        /*
         * ----------------------------------------------------
         * STEP 2
         * Position sizing
         * ----------------------------------------------------
         */
        const auto positionSizing =
            sizing::PositionSizingEngine::calculate(
                request.capital,
                request.entryPrice,
                request.stopPrice,
                config.sizingConfig);

        /*
         * ----------------------------------------------------
         * STEP 3
         * Risk management
         * ----------------------------------------------------
         *
         * The position value generated by the sizing
         * engine becomes the proposed position value.
         */
        const auto riskDecision =
            risk_management::
                RiskManagementEngine::evaluate(
                    request.capital,
                    positionSizing.positionValue,
                    request.potentialLoss,
                    request.currentDrawdown,
                    config.riskManagementConfig);

        /*
         * ----------------------------------------------------
         * STEP 4
         * Execution
         * ----------------------------------------------------
         *
         * A strategy action is executed only when
         * the proposed trade passes risk checks.
         */
        execution::ExecutionDecision
            executionDecision{
                execution::OrderSide::None,
                false};

        if (riskDecision.allowed)
        {
            executionDecision =
                execution::ExecutionEngine::evaluate(
                    strategyDecision.action);
        }

        return TradingDecision{
            strategyDecision,
            positionSizing,
            riskDecision,
            executionDecision};
    }

} // namespace quantpulse::domain::trading